### ISSUE TITLE
Is it possible to make the menu framerate match the game

### ISSUE THREAD

**Issue by Brandonspikes** [Lyall/SMTVFix#1]
This game has the same issue with P3R where the game menu is locked to 60 FPS

**Comment by tmntanno** [comment]
When you enter a menu, t.maxfps gets set to 60. Manually editing t.maxfps once in the menus will let you navigate them at custom fps but it resets once you open the menu again. No idea how this could even be fixed. 

-offtopic- The game is quite a mess since FXAA (default AA: on option) causes shimmers and forcing TAA breaks ambient occlusion but fixes all the jagged edges. Using the built-in FXAA option means resolution scaling won't work either. Either have to live with good shimmery visuals or have no ambient occlusion but have great anti-aliasing. What a dilemma.

**Comment by Lyall** [comment]
It should be easy enough to add an override to stop the framerate changing. I shall look into it.

**Comment by Lyall** [comment]
> -offtopic- The game is quite a mess since FXAA (default AA: on option) causes shimmers and forcing TAA breaks ambient occlusion but fixes all the jagged edges. Using the built-in FXAA option means resolution scaling won't work either. Either have to live with good shimmery visuals or have no ambient occlusion but have great anti-aliasing. What a dilemma.

With regards to the image quality stuff. I have found a way to have TAA and working ambient occlusion. It's the half-res ambient occlusion that breaks with TAA enabled. I will try and add an "Enable TAA" option to SMTVFix to enable this and fix the bug.

**Comment by Lyall** [comment]
Okay, in v0.8.2 I've added the option to remove the 60FPS cap in menus. That should address this issue. I've also added (and enabled by default) an option to enable TAA. If you spot any issues or have any problems, feel free to reopen the issue and yell at me.

**Comment by Iracy** [comment]
Heya, thanks for your hard work.

I just tried it out with the 60FPS fix set to true. It works on the titlescreen when selecting a save to load, but once in-game, the menu is still choppy, even though the FPS is uncapped - according to steam.

**Comment by Lyall** [comment]
> Heya, thanks for your hard work.
> 
> I just tried it out with the 60FPS fix set to true. It works on the titlescreen when selecting a save to load, but once in-game, the menu is still choppy, even though the FPS is uncapped - according to steam. It also happens in battles, when selecting the main action such as Items/Skills etc. but for some reason the skill selection itself runs buttery smooth. This was the case even without the fix you made, I thought that maybe this info could help you figure something out.

Yeah I'm not 100% sure why that is. I'm guess some of the menus must just be animated at a lower frame rate and not interpolated. Not sure what I can do about that on my end really I'm afraid.
