### ISSUE TITLE
[Feature Request] An SMTVFix.ini field to enforce specific Screen Resolutions

### ISSUE THREAD

**Issue by LOuroboros** [Lyall/SMTVFix#14]
Your P3RFix allows to set a specific screen resolution for P3R under "Custom Resolution", and I think it'd be nice if SMT5Fix could get an equivalent to that.

~~Specially because the game loves to change its resolution on its own from 1600x900 to 1440x1080 whenever I boot it up, lel.~~

**Comment by Lyall** [comment]
You can use the console command `r.setres` to set a resolution if you want. For example, `r.setres 1920x1200w` would set it to 1920x1200 windowed.
