### ISSUE TITLE
Is there a way to force 16:10 with this tool?

### ISSUE THREAD

**Issue by SMTVVPlayer** [Lyall/SMTVFix#15]
Is there a way to force 16:10 with this tool?
Sorry, my first time using github.

**Comment by Lyall** [comment]
Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.

**Comment by Skretkowicz** [comment]
Is there a way to add option to move hud elements closer to the edge of the screen? Currently since All options are for 16:9 and wider, the hud on the steam deck looks a bit out of place, kinda floating too far from the border

**Comment by Lyall** [comment]
> Is there a way to add option to move hud elements closer to the edge of the screen? Currently since All options are for 16:9 and wider, the hud on the steam deck looks a bit out of place, kinda floating too far from the border

Nope.

**Comment by SMTVVPlayer** [comment]
> Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.



> Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.

Sorry I was asking if there was a config in this tool that could force 16:10. I have a 16:10 screen and im getting black bars

**Comment by Lyall** [comment]
> > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> 
> > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> 
> Sorry I was asking if there was a config in this tool that could force 16:10. I have a 16:10 screen and im getting black bars

What resolution have you selected in-game? Also if you post your log file that might help too.

**Comment by SMTVVPlayer** [comment]
> > > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> > 
> > 
> > > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> > 
> > 
> > Sorry I was asking if there was a config in this tool that could force 16:10. I have a 16:10 screen and im getting black bars
> 
> What resolution have you selected in-game? Also if you post your log file that might help too.



> > > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> > 
> > 
> > > Should work fine at 16:10. All the HUD fixes are adapted for narrow aspect ratios as well as ultrawide. The game also doesn't restrict resolutions so if your display supports it, the game will let you use it.
> > 
> > 
> > Sorry I was asking if there was a config in this tool that could force 16:10. I have a 16:10 screen and im getting black bars
> 
> What resolution have you selected in-game? Also if you post your log file that might help too.

1280x800
Also i should point out, using the steam deck. Just trying to get rid of the annoying black bars.

**Comment by Lyall** [comment]
> 1280x800 Also i should point out, using the steam deck. Just trying to get rid of the annoying black bars. Edit, I havent installed your mod yet because I wasn't sure if it could do what I wanted. If it can i would be glad to test and post a log

It should work fine with the Steam Deck. Just bear in mind you need to add the launch parameter as detailed in the README.

**Comment by SMTVVPlayer** [comment]
It works! Thank you, sorry if my question wasn't as direct but yeah no more black bars! Thanks
