### ISSUE TITLE
Certain UI Elements shifted

### ISSUE THREAD

**Issue by Regike-** [Lyall/SMTVFix#18]
IT seems the newest version causes some issues with certain UI elements being shifted and not appearing where they are supposed to
![2024-06-18_21-44-32_SMT5V-Win64-Shipping__SHIN_MEGAMI_TENSEI_V_Vengeance](https://github.com/Lyall/SMTVFix/assets/9080626/5231291f-9b3a-4068-af4e-3b87d22002c9)
![2024-06-18_21-52-19_SMT5V-Win64-Shipping__SHIN_MEGAMI_TENSEI_V_Vengeance](https://github.com/Lyall/SMTVFix/assets/9080626/6ac78d66-825b-4d96-b9df-8e1309dc6f75)

Here is a comparison between version 0.8.5 and 0.8.6
0.8.5:
![2024-06-18_21-56-36_SMT5V-Win64-Shipping__SHIN_MEGAMI_TENSEI_V_Vengeance](https://github.com/Lyall/SMTVFix/assets/9080626/e30795b1-fabe-4129-a4a9-2dfcdc4b49f0)
0.8.6:
![2024-06-18_21-57-45_SMT5V-Win64-Shipping__SHIN_MEGAMI_TENSEI_V_Vengeance](https://github.com/Lyall/SMTVFix/assets/9080626/8797ca64-e331-4646-ba20-05fb2c7a6e3a)

I have only noticed it with these speech bubbles for now, I don't know if other elements are affected

**Comment by Lyall** [comment]
Can you post your `SMVTFix.log` file please?

**Comment by Regike-** [comment]
[SMTVFix.log](https://github.com/user-attachments/files/15892073/SMTVFix.log)

**Comment by Lyall** [comment]
Spotted the bug. You can fix it just now temporarily by keeping screen percentage at 100%, otherwise I should have a new version out soon.

**Comment by Regike-** [comment]
awesome, thanks!
