### ISSUE TITLE
r.ScreenPercentage broken on proton

### ISSUE THREAD

**Issue by VeryBigSnek** [Lyall/SMTVFix#19]
Setting r.ScreenPercentage to any value under 100 results in an EXCEPTION_INT_DIVIDE_BY_ZERO immediately crashing the game. I do not have a Windows machine to test if Windows is also effected. The bug first appeared in version 0.8.6.

**Comment by Lyall** [comment]
This is related to #18. A float was being cast as an int. It should be fixed in the next build.

**Comment by VeryBigSnek** [comment]
Good to hear, thanks!
