### ISSUE TITLE
Entering City Overworld at start of game causes crash

### ISSUE THREAD

**Issue by MeovvCAT** [Lyall/SMTVFix#2]
Game crashes when entering the overhead view of the city overworld at the start of the game post naming your character and leaving school. Saving in this area with SMTVFix disabled then loading the save with it enabled will also result in a crash.

Intro Skip: False
Dev Console: False
Aspect Ratio: True
Fix HUD: True
Fix FOV: True
Screen Percentage: 100

3400x1400 Borderless (Unlimited FPS)

**Comment by Brandonspikes** [comment]
I'm 99% sure its the .81 version, the launch version didnt crash

**Comment by MeovvCAT** [comment]
Can also confirm all battles crash as soon as the first turn starts

**Comment by MeovvCAT** [comment]
Crash does not occur in the latest version (Was hotfixed)
