### ISSUE TITLE
Increased FOV not working?

### ISSUE THREAD

**Issue by jacky-byte** [Lyall/SMTVFix#20]
Have set it to:

```
> > [Adjust Player Camera]
> ; Set to true to adjust the "Standard" camera angle preset.
> ; Default: Distance = 580 | FOV = 60 | Height = 73
> Enabled = true
> Distance = 1160
> FOV = 120
> Height = 146
```
On a standard 2560x1440 resolution, but no increase in FOV?
Other features like intro skip and remove 60fps menus are working fine.

**Comment by giever** [comment]
Are you setting in-game camera angle to "Standard"?

**Comment by Lyall** [comment]
> Are you setting in-game camera angle to "Standard"?

Yes, this is key. It doesn't affect the other camera angle presets.

**Comment by jacky-byte** [comment]
Confirmed that was the issue. Thank you guys :)
