### ISSUE TITLE
Battle transition issue in 16:9

### ISSUE THREAD

**Issue by Gav-F** [Lyall/SMTVFix#21]
Black bars flash on the top and bottom during the battle transition in 16:9. 21:9 didn't have the issue for me.

**Comment by Lyall** [comment]
Did you start the game in 21:9 then switch to 16:9? If so, that's the problem. The render texture is created on startup and doesn't get recreated when you change aspect ratio. To fix that you need to restart the game after you change aspect ratios.

**Comment by Gav-F** [comment]
Was definitely launching the game in 16:9 and still having the issue

**Comment by Lyall** [comment]
> Was definitely launching the game in 16:9 and still having the issue

Can you post your `SMTVFix.log` file please?

**Comment by Gav-F** [comment]
> > Was definitely launching the game in 16:9 and still having the issue
> 
> Can you post your `SMTVFix.log` file please?

I can after I get home

**Comment by Lyall** [comment]
Actually I think I know what the issue is. As a backup, I calculate aspect ratio from the desktop resolution first, then try to read the game resolution. The render texture must be created with that starting aspect ratio instead of the one pulled from the game. This is only manifesting for you because of the unique setup of wanting to play at 16:9 on a non-16:9 display.

**Comment by Lyall** [comment]
Hmm the render texture is created before I can even read the game resolution from memory. So having it pre-written with your desktop resolution means that you'll always be limited to your desktop resolution's aspect ratio. The ideal solution to this would be to recreate the render texture but I'm not sure how to do that 🤔.

**Comment by Lyall** [comment]
So I think for now the best option is having a toggle for this part of the fix. If, like you, someone is trying to run the game at a 16:9 when their desktop resolution is not 16:9, they can just disable that part of the fix and have it remain 16:9. 

Not a proper and complete fix but as I said before that would take updating the render texture on the fly to fix.

**Comment by Lyall** [comment]
Okay, I've added a toggle for this in v0.8.7. To fix this specific issue for you, you'll need to disable this part of the fix in `SMTVFix.ini`:
```ini
[Fix Battle Transition]
; Set to true to enable native (desktop) resolution sized 2D render textures.
; This affects the battle transition primarily. With this disabled it will remain 16:9.
Enabled = true
```

**Comment by Gav-F** [comment]
> Okay, I've added a toggle for this in v0.8.7. To fix this specific issue for you, you'll need to disable this part of the fix in `SMTVFix.ini`:
> 
> ```ini
> [Fix Battle Transition]
> ; Set to true to enable native (desktop) resolution sized 2D render textures.
> ; This affects the battle transition primarily. With this disabled it will remain 16:9.
> Enabled = true
> ```

Thanks, really appreciate it!
