### ISSUE TITLE
HDR10 Support for UE4

### ISSUE THREAD

**Issue by agentoranger** [Lyall/SMTVFix#22]
https://www.pcgamingwiki.com/wiki/Engine:Unreal_Engine_4#High_dynamic_range_.28HDR.29

I love the work you are doing here, thanks for all of your effort.  Currently. I am using Special K for Fracepacing and HDR10 tonemapping, but I was curious if SMVfix would create a better use of HDR by enabling it natively within UE4.  As with most things HDR, it can be a real can of worms so I would understand if it's not something that you wanted to look into.

Thanks for making SMTVFix, the current state of things has made big improvements to the experience.  Can I buy you a coffee or beer?

Edit: Looks like I can buy you a coffee.

**Comment by Lyall** [comment]
I'm not sure how much help I could be with this given that I don't have access to an HDR display, so testing it properly is not an option for me. Have you tried experimenting with those CVARs in-game through the console?

**Comment by agentoranger** [comment]
Not yet, as I am using Special K, I can enable HDR with its injection, it works pretty well, I will see if can test this out sometime this evening, potentially enabling this with cvar could produce a more accurate use of luminosity with more insight from UE4 and with less overhead.

**Comment by agentoranger** [comment]
The cvars do affect the color gamut and luminance in some ways and enables HDR, but it doesn't seem to be best solution for this.  I was able to product some results, but the color was either heavily over exposed or heavily under exposed.  Some elements product better luminance than Special K, but the result was all around worse in just about every way.  I really feel like this issue is not one that needs to be explored for SMTVfix, considering that tools like Special K exist, I recommend that folks use that instead, so much it requires specific tuning on a display by display basis.

Potentially, a very crafty person might be able to iterate thru all the available combinations of cvars and produce a good result, but that just didn't seem to be in the cards for me today.

**Comment by laurinius** [comment]
I'm getting really good results with RTX HDR (NvTrueHDR). FYI if anyone is using the TrueHDRTweaks, do not use their DLL, the DLL from SMTVFix will also load the asi of the tweaks.
