### ISSUE TITLE
SSGI

### ISSUE THREAD

**Issue by Octolimar** [Lyall/SMTVFix#24]
Just another suggestion; This can be set from the engine.ini but seeing as youve included GTAO, maybe also include SSGI? it provides a great improvement to indirect lighting quality. Theres r.ssgi.enable 0/1, r.ssgi.quality 1-4. and r.ssgi.halfres 0/1

I find either SSGI quality 2 to look and run great, or quality 4 with halfres enabled to also look good, though it has more artifacts.

SSAO
![20240619162046_1](https://github.com/Lyall/SMTVFix/assets/56522741/8702ced4-5de5-4f58-adbb-ae2008367f4f)

GTAO
![20240619162219_1](https://github.com/Lyall/SMTVFix/assets/56522741/14f0ac42-cbdf-431f-9d01-e5bd4163f812)

SSGI at quality level 1
![20240619162249_1](https://github.com/Lyall/SMTVFix/assets/56522741/de89f55c-2168-4073-9de5-ca37b608a182)

SSGI at quality level 2 (Recommended IMO)
![20240619162356_1](https://github.com/Lyall/SMTVFix/assets/56522741/747e9ee3-9bd0-4a43-be40-0312b4e2b77b)

SSGI at quality level 4 full res (Very demanding)
![20240619162329_1](https://github.com/Lyall/SMTVFix/assets/56522741/69af9fb4-298f-46b5-89c8-8ee82166b89a)

SSGI at quality level 4 with r.ssgi.halfres enabled
![20240619162435_1](https://github.com/Lyall/SMTVFix/assets/56522741/9d13a538-3179-4659-9aca-47fba853316e)

**Comment by Lyall** [comment]
Added in v0.8.9.
