### ISSUE TITLE
Please Read Concerning SSGI Implementation and Performance

### ISSUE THREAD

**Issue by RaygeSol** [Lyall/SMTVFix#27]
You don't need to have SSAO or GTAO on since SSGI is meant to replace those AO solutions,. You can verify this in-game with the console. 

The reason I bring this up is because if you leave SSAO/GTAO on, it will affect performance even though SSGI overrides those effects. That's just how the graphical pipeline is set up.

If the user is running both GTAO/SSAO and SSGI at the same time it will tank performance. You can test the performance gains in-game by using r.AmbientOcclusionLevels and setting it to 0 to disable AO in. You will see that you get a huge performance boost without any changes to graphical fidelity.

You can further test this by turning off SSGI using 'r.SSGI.Enable 0' in the console and turning r.AmbientOcclusionLevels to
turn the old AO on and off. 

Below is a slider with to show there are no changes other than a huge performance boost (24FPS gain in this instance.) 

[SSGI+GTAO vs SSGI Only](https://imgsli.com/MjczNDUy)

This is with using:
@5120x2880
r.ssgi.enable=1
r.ssgi.quality=2
r.ssgi.halfres=1

GTAO was set to Full Resolution

**Comment by Nud3lRick** [comment]
Thanks for the Info.

**Comment by Vladsmesh** [comment]
can you make more openworld GTAO vs SSGI comparison screenshots? ty

**Comment by Lyall** [comment]
Added an option to disable AO in v0.9.0.
