### ISSUE TITLE
Letterboxing during movies shows current/next scene.

### ISSUE THREAD

**Issue by frogles** [Lyall/SMTVFix#30]
Is it possible to have black bars without disabling the aspect ratio fix?

Intro Movie:
![image](https://github.com/Lyall/SMTVFix/assets/173485248/98dc7660-bd49-471f-b36b-b3de783a0ad0)

Game Over Movie:
![image](https://github.com/Lyall/SMTVFix/assets/173485248/728ccbd7-c745-4eb1-bb88-b0bbb64727d4)

**Comment by Lyall** [comment]
Not possible I'm afraid. The object has no background to manipulate so all you can do is adjust the movie texture. So it's either stretched movies or this.
