### ISSUE TITLE
Add option to disable Vignette

### ISSUE THREAD

**Issue by DreiPixel** [Lyall/SMTVFix#31]
Can you add a option to turn off Vignette?
the option in the console for that is "r.Tonemapper.Quality"
0 or 1 disables vignette. 2 or up to 5 enables it again. there is the possibilty that some other effects might be disabled with it tho.

> 0: basic tonemapper only, lowest quality
1: + FilmContrast
2: + Vignette
3: + FilmShadowTintAmount
4: + Grain
5: + GrainJitter = full quality (default)

**Comment by Lyall** [comment]
Added in v0.9.1.
