### ISSUE TITLE
Is it possible to disable Update Rate Optimizations at <= 60fps framerate cap?

### ISSUE THREAD

**Issue by Banz99** [Lyall/SMTVFix#32]
For those unaware, URO is responsible for halving the framerate of actors away from the player, but the range is too short to make it unnoticeable @ 60fps and it's actually egregious @ 30fps (can be easily tested inside school with the students passing by, but also with some demons). It can be disabled entirely via a.URO.Enable=0, but I don't think it's too much of a problem at higher framerates.

**Comment by Lyall** [comment]
Added in v0.9.1.
