### ISSUE TITLE
r.LandscapeLODBias=0 causes visual artifacts

### ISSUE THREAD

**Issue by merkyman** [Lyall/SMTVFix#33]
When LOD adjustments are enabled, r.LandscapeLODBias is changed from 1 to 0. This messes up the terrain in the starting location of the netherworld.

r.LandscapeLODBias=1

![20240623002131_1](https://github.com/Lyall/SMTVFix/assets/169694381/2b819f57-2d7e-47a4-9192-5970da5d1440)

r.LandscapeLODBias=0

![20240623002140_1](https://github.com/Lyall/SMTVFix/assets/169694381/33838885-c9a1-4413-a888-30997e8fc269)

I haven't compared other areas yet but I'm willing to assume such issues happen elsewhere too. With that in mind I'd suggest making that CVAR a toggleable option in the config

**Comment by ManiacPlayerXT** [comment]
Yep, same here. I turned off this option until a future fix.

**Comment by merkyman** [comment]
Also yeah it does cause artifacts in other areas

![20240624225447_1](https://github.com/Lyall/SMTVFix/assets/169694381/18723bb0-68ae-41f9-9178-8c4e7c53b86b)

For anyone too lazy to edit&compile the code here's a quick fix that doesn't touch r.LandscapeLODBias: 
[SMTVFix_asi.zip](https://github.com/user-attachments/files/15961396/SMTVFix_asi.zip)

**Comment by Lyall** [comment]
Fixed (removed) in v0.9.1.
