### ISSUE TITLE
0.9.0 - "Skip Logo = true" and "Force 4K Movies = true" both cause crash on game launch

### ISSUE THREAD

**Issue by gcp89** [Lyall/SMTVFix#34]
As stated in the title, these two options won't let the game boot for me. "Skip Logo" worked just fine with the previous version I was using, 0.8.6, so I'm not sure what the issue could be. I'm on Windows 10, by the way. That aside, thanks for the support you've given to this game and P3R.

**Comment by DreiPixel** [comment]
works for me. might be related to https://github.com/Lyall/SMTVFix/issues/23
also can you upload the log?

**Comment by gcp89** [comment]
> works for me. might be related to #23 also can you upload the log?

I've actually already gone through that one and tried all of the suggestions, but no dice, the game still won't launch with either one of those options enabled.
[SMTVFix.log](https://github.com/user-attachments/files/15973809/SMTVFix.log)

**Comment by pahamrick** [comment]
> > works for me. might be related to #23 also can you upload the log?
> 
> I've actually already gone through that one and tried all of the suggestions, but no dice, the game still won't launch with either one of those options enabled. [SMTVFix.log](https://github.com/user-attachments/files/15973809/SMTVFix.log)

I had a similar issue. What fixed it for me was deleting all the ini files located in C:\Users\*Username*\AppData\Local\SMT5V\Saved\Config\WindowsNoEditor

Can't promise its the same issue you're having, but it did fix it for me.

**Comment by gcp89** [comment]
> > > works for me. might be related to #23 also can you upload the log?
> > 
> > 
> > I've actually already gone through that one and tried all of the suggestions, but no dice, the game still won't launch with either one of those options enabled. [SMTVFix.log](https://github.com/user-attachments/files/15973809/SMTVFix.log)
> 
> I had a similar issue. What fixed it for me was deleting all the ini files located in C:\Users\Username\AppData\Local\SMT5V\Saved\Config\WindowsNoEditor
> 
> Can't promise its the same issue you're having, but it did fix it for me.

Your post helped me to narrow down the issue. It was in fact being caused by an Engine.ini command, the "r.SetRes=1920x1080f" parameter to be precise. The game now starts up fine. Thanks for the suggestion.
