### ISSUE TITLE
Is there any chance of a "Render Texture Resolution" for this game?

### ISSUE THREAD

**Issue by Tekno560** [Lyall/SMTVFix#4]
Idk if this is the place to ask this as I don't use github very often, so I apologize if this is out of place. Using 1440p right now currently leads to odd looking menus. This was a problem in P3R too, but P3Rfix had an option called "Render Texture Resolution" that fixed the issue. Wonder if it's possible for this game as well or is just impossible given base graphics.

Either way very happy to see a mod come out so quick! Thank you for your work.
Edit: the place this is most noticeable is in the images of party members, however I’m pretty certain it also applies for most of the entire menu

**Comment by zurce** [comment]
I thought i was going crazy but the menus seem to also been locked at 1080p, super disappointing since at this time does not seem to be a "bug", they are purposely limiting the menus for lower rates and lower resolution, it sucks given how much they're known for their beautiful crafted menus


I second the request for a Render Texture Resolution

**Comment by Lyall** [comment]
The UI doesn't appear to be a `TextureRenderTarget2D` like it was in P3R. If I hook the same function there's only one actual render texture that is apparently 1280x720, but what it's for, I can't tell. Increasing the resolution of that appears to do nothing.

I think the issue stems from a lot of the UI textures just being quite low res. A sign of it starting out on the Switch I guess. If you look at a quickly ripped texture sheet you can see that there's not a lot of detail. Perhaps someone could do one of those AI upscaled texture mods?

![status_01](https://github.com/Lyall/SMTVFix/assets/695941/6b36ca7f-d99b-4519-a1a2-6d3aed11377d)

**Comment by Tekno560** [comment]
Damn, that’s the outcome I was worried about. Thanks for trying and confirming what the issue actually is. Somewhat surprising they didn’t change this considering all the other work put into this version. 

Once again thank you for all of your work!
