### ISSUE TITLE
Detecting a trojan from v.0.9.1

### ISSUE THREAD

**Issue by devinbow** [Lyall/SMTVFix#41]
Windows is detecting a trojan from the latest pull, as of writing 0.9.1, Had no problems installing v.0.8.4 two weeks ago.
![Screenshot 2024-06-30 110512](https://github.com/Lyall/SMTVFix/assets/90417273/45d3433f-2cde-4fb6-a5b9-8434a0731bea)

**Comment by Lyall** [comment]
Wacatac is the generic name that Microsoft seems to use for any file that is marked as suspicious. It doesn't seem to be flagged on my end, after downloading v0.9.1 and scanning it I get this:

![image](https://github.com/Lyall/SMTVFix/assets/695941/85876952-6679-4ed1-9b1a-530da00bf44e)

I heard from another user that it was getting flagged for them too so it seems like it might have been something temporary? Are you able to try redownloading it and scanning it again? Also if you have any concerns about the legitimacy of the release builds, you can always build the latest version on your own machine. You only need to install visual studio and it should compile without any extra software.

**Comment by Iifriet** [comment]
Anything that injects code into an executable (i.e., the majority of game mods) tends to get flagged by Windows Defender. Just set it to allow it.

**Comment by Lyall** [comment]
I've seen no other reports lately of windows defender flagging the fix so I'm going to close the issue for now since it seems like it was a temporary flagging issue.
