### ISSUE TITLE
Strange lighting when TAA is enabled

### ISSUE THREAD

**Issue by angramainyuu** [Lyall/SMTVFix#42]
When enabling TAA in the .ini file it will cause the lighting/shading to change in weird ways on character faces, particularly noticeable in in-game cutscenes:

OFF:

![20240704141420_1](https://github.com/Lyall/SMTVFix/assets/98609452/3be4c768-4d2e-4aa7-9afe-bbceb1bf99ca)

ON:

![20240704135451_1](https://github.com/Lyall/SMTVFix/assets/98609452/c232fd0d-ca42-4d86-9d7a-b118730e4a91)

**Comment by Lyall** [comment]
This difference is from the full resolution ambient occlusion. UE4's TAA does not seem to work in this game with half res ambient occlusion so it's either one or the other unfortunately. You can change the look of the ambient occlusion by trying out GTAO or adjust the quality of the SSAO but I don't know of any specific way to recreate the exact look of half res SSAO.
