### ISSUE TITLE
Crashing on launch since a recent update

### ISSUE THREAD

**Issue by vittau** [Lyall/SMTVFix#43]
At least on my Steam Deck, the game is currently crashing out when launched with the patch applied.

**Comment by Lyall** [comment]
There's been no update for the game beyond v1.0.1 (on Steam) as far as I know.

![image](https://github.com/Lyall/SMTVFix/assets/695941/b5cbf5be-eba1-4f37-9d10-e8d47cc9f269)

I'd suggest trying to reinstall the latest build of SMTVFix and after launching, check to see if it produces an `SMTVFix.log` file.

**Comment by vittau** [comment]
I had tried reinstalling it and it didn't work, but apparently running the game without the patch and then reapplying it fixed it. Not sure what happened there, but it's working now. Thanks!
