### ISSUE TITLE
v0.9.6 unable to change resolution in fullscreen mode

### ISSUE THREAD

**Issue by Masselboy** [Lyall/SMTVFix#47]
Since updating to v0.9.6 I'm unable to change the resolution in fullscreen mode to anything but 4k which is my desktop resolution. Also setting screen percentage to 50 in the INI to achieve 1440p doesn't have any effect.

**Comment by Lyall** [comment]
Can you post your `SMTVFix.log` file please?

**Comment by Masselboy** [comment]
Hey Lyall, so the odd thing, today when I tried to recreate the bug to have a fresh log file ready for you, the game would correctly change resolutions again. I'm closing this issue for now. Thanks for your work!
