### ISSUE TITLE
This isn't actually an Issue, just an update for Xbox/Microsoft store

### ISSUE THREAD

**Issue by camirock17** [Lyall/SMTVFix#48]
Latest version 0.9.6 works like a charm without crashes, here are proof and the log file just in case:

![Sin título2](https://github.com/user-attachments/assets/d9fee5f1-4cc6-468c-84e1-0efdf291119b)
![Sin título2](https://github.com/user-attachments/assets/388ac0e5-ea73-45b2-8521-f199aa830cf5)
![SMT5V-WinGDK-Shipping_2024_09_01_11_14_52_673](https://github.com/user-attachments/assets/ba86fd0e-218f-4d42-ba09-41d20dda334f)
![SMT5V-WinGDK-Shipping_2024_09_01_11_14_35_091](https://github.com/user-attachments/assets/700a929a-ee98-48e8-9d8b-1b04cece3d82)
![SMT5V-WinGDK-Shipping_2024_06_19_02_22_08_569](https://github.com/user-attachments/assets/3b9a838e-1d00-44d8-944c-12d247a21724)
[SMTVFix.log](https://github.com/user-attachments/files/16829253/SMTVFix.log)

**Comment by Lyall** [comment]
That's great. Looking at your log, it looks like everything works except for two of the patterns. I'll see if I can get them working on both versions.

**Comment by camirock17** [comment]
> That's great. Looking at your log, it looks like everything works except for two of the patterns. I'll see if I can get them working on both versions.

Ty for the answer (didn't look at the two "stuff" that didn't work sincerely) hoping for a hotfix? or small fix to that.

**Comment by Lyall** [comment]
> > That's great. Looking at your log, it looks like everything works except for two of the patterns. I'll see if I can get them working on both versions.
> 
> Ty for the answer (didn't look at the two "stuff" that didn't work sincerely) hoping for a hotfix? or small fix to that.

I've updated both the patterns and they check out on the MS Store exe so it's just a matter of testing now. Would you be up for trying this build? It should fix the pattern scan failed errors in the log.

[SMTVFix_v0.9.7.zip](https://github.com/user-attachments/files/16830348/SMTVFix_v0.9.7.zip)

**Comment by camirock17** [comment]
> > > That's great. Looking at your log, it looks like everything works except for two of the patterns. I'll see if I can get them working on both versions.
> > 
> > 
> > Ty for the answer (didn't look at the two "stuff" that didn't work sincerely) hoping for a hotfix? or small fix to that.
> 
> I've updated both the patterns and they check out on the MS Store exe so it's just a matter of testing now. Would you be up for trying this build? It should fix the pattern scan failed errors in the log.
> 
> [SMTVFix_v0.9.7.zip](https://github.com/user-attachments/files/16830348/SMTVFix_v0.9.7.zip)

[SMTVFix.log](https://github.com/user-attachments/files/16830458/SMTVFix.log)
0.9.7 version

**Comment by Lyall** [comment]
Thanks for the feedback on that. Based on that new log it looks like everything is working correctly. I've put out version 0.9.7 now with these new patterns.
