### ISSUE TITLE
Update 1.0.2 : Game Crash at Launch

### ISSUE THREAD

**Issue by The-Gaymer** [Lyall/SMTVFix#49]
Since the update Today, the game crash when launch it.

**Comment by Lyall** [comment]
Seems to be working fine on my end after the update. Can you post your `SMTVFix.log` file please?

**Comment by The-Gaymer** [comment]
[SMTVFix.log](https://github.com/user-attachments/files/16862829/SMTVFix.log)
i first deleted all my mod : still crash.
I then delete your ultrawide mod : work fine :O

**Comment by The-Gaymer** [comment]
i just uninstall, and ré-install the game, then reinstall your mod, everything work fine... Weird but thanks :)

**Comment by vittau** [comment]
I had exactly the same random problem in https://github.com/Lyall/SMTVFix/issues/43
Are you on a Steam Deck?
It seems something happens randomly on the Deck sometimes, and rebooting it fixes it.
