### ISSUE TITLE
improve TAA quality

### ISSUE THREAD

**Issue by Octolimar** [Lyall/SMTVFix#5]
Enabling TAA by default results in lots of smearing on animated objects when the player is not moving. Setting r.VertexDeformationOutputsVelocity to 1 fixes this so I would recommend enforcing that change as well. Also, this version of UE4 has TSR implemented so if you could have an upsampling option that sets r.TemporalAA.Algorithm to 1 and r.TemporalAA.Upsampling to 1, it would go a long way in improving image quality, especially for people setting an internal resolution below 100%. These are great QoL changes that would help the average user see better image quality in general.

**Comment by Lyall** [comment]
So I'd already added an override for `r.TemporalAA.Algorithm` and I've now added an override for `r.VertexDeformationOutputsVelocity`. It looks like setting `r.TemporalAA.Upsampling` to 1 causes some bugs though. Here's an issue in the party menu.

`r.TemporalAA.Upsampling 1`
![SMT5V-Win64-Shipping_2024_06_15_14_59_54_719](https://github.com/Lyall/SMTVFix/assets/695941/d550b33e-ae8c-44e7-a178-deef6657d53a)

`r.TemporalAA.Upsampling 0`
![SMT5V-Win64-Shipping_2024_06_15_15_00_01_327](https://github.com/Lyall/SMTVFix/assets/695941/8d1922ea-8710-4817-93ea-44bbb0c528b9)

**Comment by Lyall** [comment]
Added (except for `r.TemporalAA.Upsampling`) in v0.8.3.
