### ISSUE TITLE
game won't launch with new update 

### ISSUE THREAD

**Issue by vandares0** [Lyall/SMTVFix#54]
hello the game won't start at all with the mod i most delete it to make the game work with the new update for game can you please look at it and thank you so much

**Comment by Lyall** [comment]
Can you post your `SMTVFix.log` file?

**Comment by vandares0** [comment]
ya sure and sorry for the  late reply  
[SMTVFix.log](https://github.com/user-attachments/files/16974765/SMTVFix.log)

**Comment by vandares0** [comment]
when i remove the  mod the game work if i put it back game refuse to start

**Comment by Lyall** [comment]
```
[2024-09-10 13:48:22.889] [SMTVFix] [info] ----------
[2024-09-10 13:48:22.889] [SMTVFix] [info] SMTVFix v0.8.8 loaded.
[2024-09-10 13:48:22.889] [SMTVFix] [info] ----------
```

You're using an old version of the fix. Download the latest version from the releases section on this repo.

**Comment by vandares0** [comment]
ty so much working like charm now  <3
