### ISSUE TITLE
0.9.8a (Xbox) spams logs while failing to hook every flag

### ISSUE THREAD

**Issue by SpaceGoat04** [Lyall/SMTVFix#55]
The latest version creates quite a big log file where it repeatedly spams "This is log message X". It doesn't load any flag therefore the game runs as is on its vanilla state:

[SMTVFix_0.9.8a.log](https://github.com/user-attachments/files/16964690/SMTVFix_0.9.8a.log)

0.9.8 works perfectly fine with every flag (including intro and movie skip):

[SMTVFix_0.9.8.log](https://github.com/user-attachments/files/16964699/SMTVFix_0.9.8.log)

Running the latest Xbox release patch (Ver.1.0.2) on Windows 10.

**Comment by Lyall** [comment]
Can you try the latest release v0.9.8b? 

It looks like I made the rather embarrassing mistake of leaving in some test code. I've removed that and reverted back another change to CVar flags which should return it to how it was in v0.9.7.

**Comment by SpaceGoat04** [comment]
Yep, everything works fine with the latest release, no log spam or non working flags

[SMTVFix_0.9.8b.log](https://github.com/user-attachments/files/16970926/SMTVFix_0.9.8b.log)
