### ISSUE TITLE
Unable to run the game

### ISSUE THREAD

**Issue by Mog-Code** [Lyall/SMTVFix#59]
Hi good day.

I just bought SMTV from steam and I can open/run it without mods, but when I extract the mods files that I got form Nexus mods to the Win64 and press Play on steam or try open the SMTV.exe, the game window wont even open. The Play button on steam will turn blue like its about to open but then it will get back to Play and we get not error message.

I'm a complete newbie when it comes to this things but I tried putting the intro skip into false and it makes the screen go black for a second like is about to open and then it gets close and we get no error message.
[Intro Skip]
; Set to true to skip intro logos. You can also skip the opening movie.
Enabled = false
SkipMovie = false

I really want to try this games with mods, I hope you could help me.

**Comment by KonnoYK** [comment]
Try to download the newest released version in github which is v0.9.9 . I hope it could help you

**Comment by Mog-Code** [comment]
> Try to download the newest released version in github which is v0.9.9 . I hope it could help you

Ok thank you I try that.

**Comment by Mog-Code** [comment]
It worked. Thank you for you quick reply.
