### ISSUE TITLE
Possible to align the hud to the edges for ultrawide?

### ISSUE THREAD

**Issue by Ser-Noodles** [Lyall/SMTVFix#6]
Hi, not really an issue I know 
But would it be possible to have an option to align the hud to the edges of the screen for ultrawide monitors, rather than just the 16:9 option that's there currently? 
I personally prefer when the HUD is off to the side so I can see more of the game in front of me.

If not that's totally fine, thanks so much for your work on this I can't believe you were able to put this out so quickly, it's made my game so much better!

**Comment by Lyall** [comment]
This is probably not feasible since it would likely require modifying many HUD assets. I'm not writing it off completely, but for now it's not on the table.

**Comment by Ser-Noodles** [comment]
No worries thanks for your reply. And thanks again for your work it's fantastic!
