### ISSUE TITLE
Game refuses to launch with mod installed

### ISSUE THREAD

**Issue by Nariod14** [Lyall/SMTVFix#60]
Greetings! I understand that all issues are to be posted here, so here I am. I have just followed the instructions to install the mod, copying and pasting all the files to the Win64 folder, but it seems that when those files are present, the game refuses to launch at all. Doubleclicking the executable or running the game through steam seem to do absolutely nothing, and the game runs fine again when I remove all the files. I've included the SMTVFix text file, which I assume to be logs in case they may help.

Thanks for your effort in modding regardless, it is much appreciated!
[SMTVFix.log](https://github.com/user-attachments/files/17580002/SMTVFix.log)

**Comment by Lyall** [comment]
Your log says you're using v0.8.8, that's quite old. Can you try the latest build?
https://github.com/Lyall/SMTVFix/releases/tag/v0.9.9

**Comment by Nariod14** [comment]
Sorry about the late reply, it seems this got buried in my email. That was the version I downloaded off Nexus. I just tried the newest version though and It works like a charm. No crashes on launch or anything thus far. Thanks for making mods like this and still maintaining the issues page!
