### ISSUE TITLE
Latest Patch (1.03) Broke SMTVFix

### ISSUE THREAD

**Issue by gumbylicious** [Lyall/SMTVFix#61]
As far as I can tell... the latest patch 1.03—released November 4, 2024—broke SMTVFix. Can't get it to take no matter how many clean installs. (Insanity is reinstalling over and over and expecting something to change.) 

Unless I'm missing something simple that's preventing it from working.

I appreciate your work, thank you

**Comment by Lyall** [comment]
Seems to still be working fine for me. Can you post your `SMTVFix.log` file please?

**Comment by gumbylicious** [comment]
I would but I'm not able to generate a log file after launching, which was what originally made me think the patch had been the issue. Using SMTVFix_v0.9.9. 

I'm on the Steam version. It's extracted into \steamapps\common\SMT5V\Project\Binaries\Win64.

Tried running as admin; verifying the integrity; tried launching the SMT5V-Win64-Shipping.exe.

**Comment by gumbylicious** [comment]
[SMTVFix.log](https://github.com/user-attachments/files/17621654/SMTVFix.log)

Using the Reloaded II version (after removing the Steam version) I was able to generate a log file. Though it doesn't appear to work still, as with skip intro/logos enabled I'm still seeing them. 

I see these errors: 

[2024-11-04 10:13:33.402] [SMTVFix.log] [error] Offsets: GObjects: Pattern scan failed.
[2024-11-04 10:13:33.403] [SMTVFix.log] [error] Offsets: AppendString: Pattern scan failed.
[2024-11-04 10:13:33.403] [SMTVFix.log] [error] Offsets: ProcessEvent: Pattern scan failed.
[2024-11-04 10:13:33.404] [SMTVFix.log] [error] Current Resolution: Pattern scan failed.
[2024-11-04 10:13:33.404] [SMTVFix.log] [error] Console CVARs: Pattern scan failed.

**Comment by Lyall** [comment]
It appears to be injecting into the game's launcher file and not the shipping exe that it should be. Where did you have your ASI loader deployed to?

You'll want the ASI loader file (`dsound.dll`) next to `SMT5V-Win64-Shipping.exe` in `Steam\steamapps\common\SMT5V\Project\Binaries\Win64`

**Comment by gumbylicious** [comment]
With the Reloaded II version I don't see dsound.dll. 

It installed under \Reloaded-II\Mods\smtvv.smtvfix with MonConfig.json, SMTVFix.asi, SMTVFix.ini, and then, after launching, SMTVFix.log in that folder. 

So I removed the Reloaded II version and went back to the Steam version: dsound.dll is next to SMT5V-Win64-Shipping.exe in Steam\steamapps\common\SMT5V\Project\Binaries\Win64

But no log file after launching. 

Could it be because I'm installing in an E drive?

**Comment by Lyall** [comment]
No that's unlikely. So you have `dsound.dll`, `SMTVFix.asi` and `SMTVFix.ini` next to `SMT5V-Win64-Shipping.exe` in the `Binaries\Win64` folder, yes?

**Comment by gumbylicious** [comment]
Yes sir, that's correct. 

I did a fresh install on my other drive. Installed the Steam version. This is what the folder looks like:

![explorer_ccer7lz74k](https://github.com/user-attachments/assets/2ad1130a-d83c-4d6d-b04b-43388475d5b4)

And this time it did generate a log file. No errors that I see: 

[SMTVFix.log](https://github.com/user-attachments/files/17622039/SMTVFix.log)

I have the console hotkey setup as well under %LOCALAPPDATA%\SMT5V\Saved\Config\WindowsNoEditor\Input.ini

But no go.

**Comment by gumbylicious** [comment]
OK. I got it work. I don't know why this works. 

But after installing Reloaded II again, without removing the Steam files, the mod now works. 

Thank you for your patience with my ignorance. I don't know what changed, but I'm not going to question it. 

Much appreciated!

**Comment by n0tleinad** [comment]
Hello, to me the mod doesn't work after it (yes i reported about a bug from the MS Store version but now i bought the steam version lol)
The mod executes but somehow nothing applies because it generates a log and everything 
Here's my Log file, im on Linux if that makes sense, yes, im using the launch commands for the Linux/Steam deck compatibility 
I don't use ReloadedII
[SMTVFix.log](https://github.com/user-attachments/files/17625621/SMTVFix.log)

**Comment by n0tleinad** [comment]
I don't know what the hell happened but i rebooted the game and it worked again?
Forget everything lmao, sorry for the useless notification
