### ISSUE TITLE
game fails to launch with fix installed

### ISSUE THREAD

**Issue by fluffybillygoat** [Lyall/SMTVFix#62]
I have tried disabling every setting and the only thing that makes a difference is turning off the intro skip. With the intro skip disabled it will launch to a black screen for a couple of seconds then close. With it enabled, no window will open. This was not a problem on my previous computer so it's even more confusing. It was the same file in the same SSD from the previous PC launched with steam and didn't work. .

**Comment by Lyall** [comment]
Can you post your log file please?

**Comment by fluffybillygoat** [comment]
> Can you post your log file please?

How do I get that? Sorry I haven't done something like this before

**Comment by Lyall** [comment]
> > Can you post your log file please?
> 
> How do I get that? Sorry I haven't done something like this before

There will be a `SMTVFix.log` file next to the main shipping executable in `steamapps\common\SMT5V\Project\Binaries\Win64`.

**Comment by fluffybillygoat** [comment]
[SMTVFix.log](https://github.com/user-attachments/files/17637186/SMTVFix.log)

**Comment by Lyall** [comment]
You're using an old version of the fix (v0.8.8). Download the latest one (v0.9.9) from the [releases section](https://github.com/Lyall/SMTVFix/releases) of this repository.

**Comment by fluffybillygoat** [comment]
> You're using an old version of the fix (v0.8.8). Download the latest one (v0.9.9) from the [releases section](https://github.com/Lyall/SMTVFix/releases) of this repository.

Ah, I was using the download posted on Nexus, working now.

**Comment by Lyall** [comment]
> > You're using an old version of the fix (v0.8.8). Download the latest one (v0.9.9) from the [releases section](https://github.com/Lyall/SMTVFix/releases) of this repository.
> 
> Ah, I was using the download posted on Nexus, working now.

Yeah that Nexus Mods version was not added by me, so the uploader has let it go out of date. I only recently started posting my own stuff on Nexus.
