### ISSUE TITLE
When I install the mod and start the game, it crashes.

### ISSUE THREAD

**Issue by RainbowAx** [Lyall/SMTVFix#64]
I installed the mod with NEXUSMODS and extracted it to [SMT5V\Project\Binaries\Win64].

But as soon as I try to start the game, the game crashes.

The [SMTVFix.log] was output and I am attaching it, but there did not seem to be any errors.
[SMTVFix.log](https://github.com/user-attachments/files/17720200/SMTVFix.log)

**Comment by Lyall** [comment]
The nexus mods version is not uploaded by me and is therefore out of date. Download the latest version from the releases section on this repo and give that a try.

**Comment by RainbowAx** [comment]
I installed v0.9.9 and the game started without problems.

Thank you for your reply, it was a rudimentary question.
