### ISSUE TITLE
Fix not working after the latest update.

### ISSUE THREAD

**Issue by JGration** [Lyall/SMTVFix#65]
Whenever i try to open the game with the SMTVFix, it just crashes to desktop. Any ideas?

**Comment by Lyall** [comment]
Post your `SMTVFix.log` file.

**Comment by JGration** [comment]
Here

[SMTVFix.log](https://github.com/user-attachments/files/17740638/SMTVFix.log)

**Comment by Lyall** [comment]
You're using an old version. Grab the latest release from this repo.

**Comment by JGration** [comment]
Oh sorry that was stupid of me, thanks for pointing it out!
