### ISSUE TITLE
Add an option for GTAO instead of the standard SSAO

### ISSUE THREAD

**Issue by Banz99** [Lyall/SMTVFix#7]
Just noticed that changing r.AmbientOcclusion.Method from 0 to 1 allows you to change this, and there seems to be no downsides except for performance.
I think it's a much better solution (way less exaggerated), maybe it could be integrated as a ini option.

No AO:
![image](https://github.com/Lyall/SMTVFix/assets/42299919/d57ace4a-ca91-49c1-aeec-dfff40763a0b)

SSAO:
![image](https://github.com/Lyall/SMTVFix/assets/42299919/9d428252-602a-4332-b59d-cefb2faaecca)

GTAO:
![image](https://github.com/Lyall/SMTVFix/assets/42299919/803e801f-9e94-4042-b3ae-4093d27c1006)

**Comment by Lyall** [comment]
Does setting this in `Engine.ini` work? If so, I'm hesitant to add anything that isn't being overridden by the game as you can just use `Engine.ini` to set them in that case.

**Comment by Octolimar** [comment]
I know ssgi can be enabled by the engine.ini and works great

**Comment by Oneline8** [comment]
Would be great if you added a separate option for the full resolution ambient occlusion (which is enabled with TAA). When enabled, shadows look terrible compared to default setting (no mod) and GTAO. Easy to notice in MC's room: there're huge black spots behind the clothes hanging againts the wall.

**Comment by Banz99** [comment]
> Does setting this in `Engine.ini` work? If so, I'm hesitant to add anything that isn't being overridden by the game as you can just use `Engine.ini` to set them in that case.

It can be enabled that way, yes. But so could r.ScreenPercentage for that matter. Up to you

**Comment by Lyall** [comment]
Added in v0.8.4.
