### ISSUE TITLE
Skipping intro logos does not work as of 0.8.3

### ISSUE THREAD

**Issue by Iifriet** [Lyall/SMTVFix#8]
It was working in 0.8.2. Does not appear to matter if the SkipMovie ini toggle is set to true or false. (yes I have it set to Enabled = true in the ini)

**Comment by Lyall** [comment]
Can you try redownloading v0.8.3? I've just put out a quick re-upload with the fix applied.

**Comment by Iifriet** [comment]
> Can you try redownloading v0.8.3? I've just put out a quick re-upload with the fix applied.

Intro logo skip now works; setting SkipMovie to true results in a crash at launch.

**Comment by Lyall** [comment]
Can you try v0.8.3 one more time? Should be fixed now that I've added some checks. This is what I get for pushing updates in the middle of the night!

**Comment by Iifriet** [comment]
> Can you try v0.8.3 one more time? Should be fixed now that I've added some checks. This is what I get for pushing updates in the middle of the night!

Skipping of intro logos and movie now both work. TYVM for the mod btw

**Comment by Lyall** [comment]
> > Can you try v0.8.3 one more time? Should be fixed now that I've added some checks. This is what I get for pushing updates in the middle of the night!
> 
> Skipping of intro logos and movie now both work. TYVM for the mod btw

Awesome, and thank you for spotting that! Might have missed it until the morning.
